In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Max\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.9.2-py37haa95532_0




conda-4.9.2          | 2.9 MB    |            |   0% 
conda-4.9.2          | 2.9 MB    |            |   1% 
conda-4.9.2          | 2.9 MB    | #4         |  15% 
conda-4.9.2          | 2.9 MB    | ##4        |  25% 
conda-4.9.2          | 2.9 MB    | #####7     |  57% 
conda-4.9.2          | 2.9 MB    | #######1   |  72% 
conda-4.9.2          | 2.9 MB    | ########5  |  86% 
cond

In [4]:
import numpy as np

In [12]:
#1.生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。
a=np.linspace(0,20,num=21,retstep=True)
a

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20.]), 1.0)

In [30]:
#2.呈上題，將以上數列取出偶數
a=np.linspace(0,20,num=21)
a[0:20:2]

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [32]:
#3.呈 1 題，將數列取出 3 的倍數。
a[3:20:3]

array([ 3.,  6.,  9., 12., 15., 18.])